# .streamlit/secrets.toml
[connections.snowflake]
account = "XAUSHBE-DINNER"
user = "DINNER_ADMIN"
password = "Yay123456"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true